name: Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2.0.0
        with:
          path: .gradle
          key: gradle

      - name: Build
        run: ./gradlew clean assemble

      - name: Upload Github Pages
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ./build/distributions/github-pages.tar.gz
          retention-days: 1